[project]
name = "onvolunteers-notebook-scripts"
version = "0.1.0"
description = "Scripts for OnVolunteers notebook"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "playwright",
]
